before_install:
  - export TZ=America/Los_Angeles
language: ruby
rvm:
  - 2.3.3
script:
  - JEKYLL_ENV=production ./bin/jekyll build
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./bin/s3_website push; fi
