---
encoding: utf-8
permalink: /:year/:month/:title/
title: connecting the tubes
description: Ventilations from an engineer — Stephen Crosby is an Internet
  engineer and explorer of the worldwide series of tubes
url: http://lithostech.com
sass:
  sass_dir: _sass
exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - s3_website.yml
feed:
  layout: feed.xml
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
excerpt_separator: <!--more-->
assets:
  sources:
    - _assets
defaults:
  -
    scope:
      path: ""
    values:
      author:
        name: Stephen Crosby
        email: "stevecrozz@gmail.com"
responsive_image:
  template: _includes/responsive-image.html
  default_quality: 90
  sizes:
    - width: 200
    - width: 300
    - width: 600
  base_path: static/img/full
  output_path_format: assets/%{dirname}/%{width}/%{basename}
gems:
  - jekyll-assets
  - jekyll/responsive_image
