---
encoding: utf-8
permalink: /:year/:month/:title/
sass:
  sass_dir: _sass
exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - s3_website.yml
paginate: 5
paginate_path: "page/:num/"
markdown: kramdown
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: table
    coderay_css: class
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: ""
    values:
      author:
        name: Stephen Crosby
        email: "stevecrozz@gmail.com"
picture:
  source: "static/img/full"
  output: "static/img/resize"
  markup: "picture"
  presets:
    thumbnail-left:
      attr:
        class: "thumbnail left"
        itemprop: "image"
      source_small:
        media: "(min-width: 576px)"
        width: "300"
      source_default:
        width: "200"
    thumbnail-right:
      attr:
        class: "thumbnail right"
        itemprop: "image"
      source_small:
        media: "(min-width: 576px)"
        width: "300"
      source_default:
        width: "200"
    full:
      attr:
        class: "thumbnail full"
        itemprop: "image"
      source_medium:
        media: "(min-width: 768px)"
        width: "1024"
      source_small:
        media: "(min-width: 405px)"
        width: "600"
      source_default:
        width: "300"
