---
encoding: utf-8
permalink: /:year/:month/:title/
title: connecting the tubes
description: Ventilations from an engineer — Stephen Crosby is an Internet
  engineer and explorer of the worldwide series of tubes
url: http://lithostech.com
exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - s3_website.yml
  - vendor
feed:
  layout: feed.xml
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: ""
    values:
      author:
        name: Stephen Crosby
        email: "stevecrozz@gmail.com"
responsive_image:
  template: _includes/responsive-image.html
  default_quality: 90
  sizes:
    - width: 200
    - width: 300
    - width: 600
  base_path: static/img/full
  output_path_format: static/img/resized/%{width}/%{basename}
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
plugins:
  - jekyll-responsive-image
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-sitemap
